### ISSUE TITLE
Memory Computation

### ISSUE THREAD

**Issue by techmonsterwang** [TAMU-VITA/AGD#11]
Hi, I find the paper compare memory(MB) in the table.

Works in model compression field always compare parameters(M) in their results.

So are there any differences and what's memory means?

**Comment by tilmto** [comment]
The compression field always adopts number of parameters (M) while here we adopt the memory consumption of the parameters (MB) following our baseline CEC. For example, if the model has 1M parameters which are stored in 32-bit format, then the memory consumption will be 1M * 32bit = 32Mb = 4MB.

**Comment by techmonsterwang** [comment]
Thanks for your answer!
So does "which are stored in 32-bit format" means the following: 

Assuming that the parameters are stored as a floating number, it occupies 4 bytes on a 32-bit system, that is, 32 bits

**Comment by tilmto** [comment]
Yes, 32-bit is the default precision in DL frameworks like pytorch. We also have an experiment setting with 8-bit quantization, where 1M params lead to 1MB memory consumption.

**Comment by techmonsterwang** [comment]
Thanks for replying!
