### ISSUE TITLE
Does this way can apply to image-to-image translation model?

### ISSUE THREAD

**Issue by forest520** [TAMU-VITA/AGD#16]
Such as Pix2PixHD? Thanks!

**Comment by tilmto** [comment]
Yes, our method is generally applicable to image-to-image translation tasks like Pix2PixHD.

**Comment by forest520** [comment]
And what is the difference between GAN-Slimming and this method? For Pix2PixHD compression, which one might be better? Thanks!

**Comment by tilmto** [comment]
GAN-slimming aims to trim down the complexity of existing SOTA generator designs, while this work searches for a new generator architecture in a predefined search space. It's hard to say which one is better on Pix2PixHD. If you aim at compressing SOTA models on Pix2PixHD, you may prefer GAN slimming and if you have expert knowledge about what's a good design space for Pix2PixHD, then you can adopt our NAS-based method with updated search space.
