### ISSUE TITLE
How to observe the results?

### ISSUE THREAD

**Issue by eps696** [TAMU-VITA/AGD#2]
hello,
i've got somewhat dumb straightforward question:
i have completed the distillation process for SR model (took 5 days on 1080ti). the result was ~550mb model, reported as having 0.75M params (two orders of magnitude less than original teacher model), performing with 356 GFLOPS (rather close to the original). your recently provided models have about the same characteristics (550mb, 0.54M and 316G respectively). the speed of processing also stayed the same as the original (teacher) SR model.
how can i observe speedup and size decrease, mentioned in the repo readme?

**Comment by tilmto** [comment]
The GFLOPs is determined by the input image size. If the input size is 256*256, the computation of original ESRGAN will be 1176.61 GFLOPs, while the one of AGD will be 108.06 GFLOPs (10x smaller). Did you control the same input size? BTW, how did you calculate the GFLOPs of original ESRGAN (two orders of magnitude less params with similar FLOPs does not make sense)?

**Comment by eps696** [comment]
i meant log messages printed out during training procedure - that's the only metrics i noticed. so i compared values at the beginning of the first stage and at the end of the last one. of course, i didn't change resolution or anything during training process.

**Comment by tilmto** [comment]
These logs are not the FLOPs of the original ESRGAN, instead they are the FLOPs of the searched networks at each searching epoch, which are calculated with the average input size of training dataset DIV2K (510*350). The flops of the final model on the evaluation dataset (Set5, Set14, Urban100, BSD100) can be found in the Readme or the paper. BTW, if you are interested in reproducing the FLOPs of the original ESRGAN, your can use thop package to measure the provided model in their official github https://github.com/xinntao/ESRGAN.
