### ISSUE TITLE
Why flops_weight = 0？

### ISSUE THREAD

**Issue by buwangchuxin1992** [TAMU-VITA/AGD#23]
Thanks for your work,I try reproduce your work.In your config_search.py,your  C.flops_weight = 0.If do so,the loss_flops is always  0,how to constrain the flops of model archtecture? I wonder if I am wrong,thanks

**Comment by tilmto** [comment]
Hi, you are right that C.flops_weight should be a positive number and we use C.flops_weight=1e-17 for the image translation task: https://github.com/VITA-Group/AGD/blob/616a10a583d1d2e280585d083fd17bc555f0f93a/AGD_ST/search/config_search.py#L157 For the super-resolution task, we didn't record the best setting as this project was done 3-4 years ago while a suggested practice is to set C.flops_weight between 1e-11 ~ 1e-17, which can achieve good accuracy-efficiency trade-off.

**Comment by buwangchuxin1992** [comment]
Thanks.More,I find
 `    C.loss_weight = [1e-2, 0, 1, 0]`  in config_search.py in search stage
which is different from your  paper 
![image](https://github.com/VITA-Group/AGD/assets/23277799/faf7d0cc-50e5-4d29-9167-0c06600301f7)
  I wonder which one should I choose（super resolution task）?thanks

**Comment by tilmto** [comment]
You can follow the settings in our paper.

**Comment by buwangchuxin1992** [comment]
Thanks for your reply.
