### ISSUE TITLE
How to visualize the learned cell?

### ISSUE THREAD

**Issue by yiyunchen** [TAMU-VITA/AGD#4]
Hello, would you mind tell me how to visualize the learned cell?

I see the related code "from utils.darts_utils import create_exp_dir, save, plot_op, plot_path_width, objective_acc_lat"?
or how can I get the seach results?

Thank you !

**Comment by tilmto** [comment]
Hi, you can use the following script to visualize the searched architecture stored at ckpt/search-xxx/arch.pt with:
```
python print_arch.py ckpt/search-xxx/arch.pt
```
The code in print_arch.py:
```
# print_arch.py

import torch
import sys

model = torch.load(sys.argv[1])
alpha= model['alpha']
ratio = model['ratio']

print(alpha.argmax(-1)) # layerwise operator index, see genotypes.py for their corresponding operator
print(ratio.argmax(-1)) # layerwise width index, see C.width_mult_list in config_search.py
```

**Comment by yiyunchen** [comment]
Thank you！
